In [1]:
import torch
from torch import nn
from torch.nn import functional as F

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return x - x.mean()

In [3]:
layer = CenteredLayer()
x = torch.tensor([1.0, 2, 3, 4, 5])
print(x.mean())
layer(x)

tensor(3.)


tensor([-2., -1.,  0.,  1.,  2.])

In [4]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())

In [5]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-3.7253e-09, grad_fn=<MeanBackward0>)

In [6]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [7]:
linear = MyLinear(5, 3)
print(linear.weight, linear.bias)
print(linear.weight.shape, linear.bias.shape)

Parameter containing:
tensor([[ 0.4080,  1.6750,  0.5342],
        [-0.6703, -1.0808, -1.3784],
        [ 0.0540, -0.4243,  1.0899],
        [-1.2087,  1.1785,  0.7787],
        [-0.1897,  0.4594,  1.2639]], requires_grad=True) Parameter containing:
tensor([-0.9063, -0.0114,  0.4973], requires_grad=True)
torch.Size([5, 3]) torch.Size([3])


In [8]:
linear(torch.rand(2, 5))

tensor([[0.0000, 2.1912, 1.7331],
        [0.0000, 0.3071, 1.4635]])

In [9]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[40.8397],
        [46.1035]])